In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
data = pd.read_csv('housing.csv')
data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [4]:
data.info() #data.isnull().any()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [5]:
data.dropna(inplace=True)

In [6]:
data.info() #data.isnull().any()

<class 'pandas.core.frame.DataFrame'>
Index: 20433 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20433 non-null  float64
 1   latitude            20433 non-null  float64
 2   housing_median_age  20433 non-null  float64
 3   total_rooms         20433 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20433 non-null  float64
 6   households          20433 non-null  float64
 7   median_income       20433 non-null  float64
 8   median_house_value  20433 non-null  float64
 9   ocean_proximity     20433 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.7+ MB


In [7]:
x = np.array(data)[:, :8].astype(np.float32)
x

array([[-1.2223e+02,  3.7880e+01,  4.1000e+01, ...,  3.2200e+02,
         1.2600e+02,  8.3252e+00],
       [-1.2222e+02,  3.7860e+01,  2.1000e+01, ...,  2.4010e+03,
         1.1380e+03,  8.3014e+00],
       [-1.2224e+02,  3.7850e+01,  5.2000e+01, ...,  4.9600e+02,
         1.7700e+02,  7.2574e+00],
       ...,
       [-1.2122e+02,  3.9430e+01,  1.7000e+01, ...,  1.0070e+03,
         4.3300e+02,  1.7000e+00],
       [-1.2132e+02,  3.9430e+01,  1.8000e+01, ...,  7.4100e+02,
         3.4900e+02,  1.8672e+00],
       [-1.2124e+02,  3.9370e+01,  1.6000e+01, ...,  1.3870e+03,
         5.3000e+02,  2.3886e+00]], dtype=float32)

In [8]:
y = np.array(data)[:, 8].astype(np.float32)
y

array([452600., 358500., 352100., ...,  92300.,  84700.,  89400.],
      dtype=float32)

In [9]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [10]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((16346, 8), (4087, 8), (16346,), (4087,))

In [11]:
x_train[0], y_train[0]

(array([-121.8   ,   37.32  ,   14.    , 4412.    ,  924.    , 2698.    ,
         891.    ,    4.7027], dtype=float32),
 227600.0)

In [12]:
from sklearn.pipeline import Pipeline

# regressor

- Poly + Ridge
- SVR ( poly )
- SGD ( epsilon_insensitive )
- DecisionTreeRegressor

### Poly + Ridge

In [13]:
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.linear_model import Ridge

ridge_reg = Pipeline([
  ('poly', PolynomialFeatures(degree=3, include_bias=False)),
  ('scal', StandardScaler()),
  ('ridge', Ridge(alpha=0.1, random_state=42))
])

ridge_reg.fit(x_train, y_train)

/opt/homebrew/Caskroom/miniconda/base/envs/sklearn-env/lib/python3.12/site-packages/sklearn/linear_model/_ridge.py:204: LinAlgWarning: Ill-conditioned matrix (rcond=1.83401e-08): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T


Pipeline(steps=[('poly', PolynomialFeatures(degree=3, include_bias=False)),
                ('scal', StandardScaler()),
                ('ridge', Ridge(alpha=0.1, random_state=42))])

In [14]:
ridge_reg.score(x_train, y_train), ridge_reg.score(x_test, y_test)

(0.7353013510037198, 0.7223518192306464)

### SVR

In [26]:
from sklearn.svm import SVR

poly_svr_reg = Pipeline([
  ('poly', PolynomialFeatures(degree=3, include_bias=False)),
  ('scal', StandardScaler()),
  ('svr', SVR(kernel="poly", degree=2, epsilon=0.1, gamma=1))
])

poly_svr_reg.fit(x_train, y_train)

Pipeline(steps=[('poly', PolynomialFeatures(degree=3, include_bias=False)),
                ('scal', StandardScaler()),
                ('svr', SVR(degree=2, gamma=1, kernel='poly'))])

In [27]:
poly_svr_reg.score(x_train, y_train), poly_svr_reg.score(x_test, y_test)

(0.5878259799684082, 0.5655157543864402)

### SGD ( epsilon_insensitive )

In [17]:
# from sklearn.linear_model import SGDRegressor

# poly_sgd_reg = Pipeline([
#   ("poly", PolynomialFeatures(degree=2, include_bias=False)),
#   ("scal", StandardScaler()),
#   ("poly_sgd", SGDRegressor(loss="epsilon_insensitive", epsilon=0.1, random_state=42))
# ])

# poly_sgd_reg.fit(x_train, y_train)

In [18]:
# poly_sgd_reg.score(x_train, y_train), poly_sgd_reg.score(x_test, y_test)

### DecisionTreeRegressor

In [19]:
from sklearn.tree import DecisionTreeRegressor

tree_reg = Pipeline([
  ("poly", PolynomialFeatures(degree=2, include_bias=False)),
  ("scal", StandardScaler()),
  ("tree", DecisionTreeRegressor(max_depth=2, random_state=42))
])

tree_reg.fit(x, y)

Pipeline(steps=[('poly', PolynomialFeatures(include_bias=False)),
                ('scal', StandardScaler()),
                ('tree', DecisionTreeRegressor(max_depth=2, random_state=42))])

In [20]:
tree_reg.score(x_train, y_train)

0.4494981684388486

### Ensemble Learning

In [22]:
from sklearn.ensemble import VotingRegressor

voting_reg = VotingRegressor([
  ('ridge_reg', ridge_reg),
  ('poly_svr_reg', poly_svr_reg),
  # ('poly_sgd_reg', poly_sgd_reg),
  ('tree_reg', tree_reg)
])

voting_reg.fit(x_train, y_train)

/opt/homebrew/Caskroom/miniconda/base/envs/sklearn-env/lib/python3.12/site-packages/sklearn/linear_model/_ridge.py:204: LinAlgWarning: Ill-conditioned matrix (rcond=1.83401e-08): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T


VotingRegressor(estimators=[('ridge_reg',
                             Pipeline(steps=[('poly',
                                              PolynomialFeatures(degree=3,
                                                                 include_bias=False)),
                                             ('scal', StandardScaler()),
                                             ('ridge',
                                              Ridge(alpha=0.1,
                                                    random_state=42))])),
                            ('poly_svr_reg',
                             Pipeline(steps=[('poly',
                                              PolynomialFeatures(degree=3,
                                                                 include_bias=False)),
                                             ('scal', StandardScaler()),
                                             ('svr',
                                              SVR(degree=2, gamma=1,
                                                  kernel='poly'))])),
                            ('tree_reg',
                             Pipeline(steps=[('poly',
                                              PolynomialFeatures(include_bias=False)),
                                             ('scal', StandardScaler()),
                                             ('tree',
                                              DecisionTreeRegressor(max_depth=2,
                                                                    random_state=42))]))])

In [23]:
voting_reg.score(x_train, y_train), voting_reg.score(x_test, y_test)

(0.6563373093176028, 0.6435886109517193)